import core.BaseTest;
import driver.DriverManager;
import io.appium.java_client.AppiumBy;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidTouchAction;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.PointerInput;
import org.testng.Assert;
import org.testng.ITest;
import org.testng.annotations.Test;

import org.openqa.selenium.interactions.Sequence;
import org.openqa.selenium.remote.RemoteWebElement;

import com.google.common.collect.ImmutableList;

import pages.Home.HomePage;
import pages.Login.LoginPage;
import pages.Settings.ActivatePage;
import pages.Settings.SettingPage;
import pages.Settings.SyncModelPage;
import utils.PageUtils;
import utils.TestGesture;

import java.lang.reflect.Method;
import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.util.Arrays;
import java.util.Base64;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.Map;

import java.lang.reflect.Method;

public class mobileTests extends BaseTest{
    @Test
    public void testExample() {
        int actualValue = 5;
        int expectedValue = 5;
        Assert.assertEquals(actualValue, expectedValue, "Giá trị không khớp");
    }
    @Test
    public void activateTest(Method m) throws InterruptedException {
        new LoginPage().clickOnSettings();
        new SettingPage().clickOnActivate();
        new ActivatePage().sendKeyActCode("01EFSFRQ7WJSWVK15HJB4S4X3N");
        new ActivatePage().sendKeyName("automateTest");
        new ActivatePage().clickOnSave();
        Thread.sleep(5000);
        new SettingPage().clickOnTest();
        new SettingPage().goBack();

        Assert.assertEquals(new SettingPage().checkToastMessageIsCorrect("ok", m.getName()),true,"Activate is not successful");
    }
    @Test
    public void syncModelTest() throws InterruptedException {
        new LoginPage().clickOnSettings();
        new SettingPage().clickOnSyncModel();

        new SyncModelPage().changeTestEnv();
        new SyncModelPage().clickOnSyncAllModel();
        Thread.sleep(20000);
        System.out.println("Sync done bat dau quay lai");
        new SyncModelPage().goBack();
        new SyncModelPage().goBack();
        new SyncModelPage().goBack();
    }
    @Test
    public void loginTest() throws InterruptedException {
        new LoginPage().sendKeyUsername("tuan.pham");
        new LoginPage().sendKeyPassword("12345");
        new LoginPage().clickOnLogin();
        Thread.sleep(10000);
        Assert.assertEquals(new HomePage().isElementPresent(AppiumBy.xpath("//android.widget.LinearLayout[@resource-id=\"pocketv.datavtech.application:id/action_bar_root\"]")),
                true,"Login failed");
    }

    @Test
    public void DVTCaseToCall() throws InterruptedException {
        WebDriver driver = DriverManager.getDriver();
        WebElement el1 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Field Service Management\")"));
        el1.click();
        WebElement el2 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(0)"));
        el2.click();
        WebElement el3 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el3.click();
        WebElement el4 = driver.findElement(AppiumBy.id("android:id/text1"));
        el4.click();
        WebElement el5 = driver.findElement(AppiumBy.accessibilityId("txtDescription"));
        el5.click();
        el5.sendKeys("Check printer machine");
        WebElement el6 = driver.findElement(AppiumBy.accessibilityId("btnPerCont"));
        el6.click();
        WebElement el7 = driver.findElement(AppiumBy.accessibilityId("btnLoadData"));
        el7.click();
        WebElement el8 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(10)"));
        el8.click();
        TestGesture.scrollById("txtIssueDesc");
        Thread.sleep(1000);
        WebElement el9 = driver.findElement(AppiumBy.accessibilityId("txtIssueDesc"));
        el9.click();
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("btnSearchPart");
        Thread.sleep(1000);
        WebElement el10 = driver.findElement(AppiumBy.accessibilityId("btnSearchPart"));
        el10.click();
        WebElement el11 = driver.findElement(AppiumBy.accessibilityId("btnSearchKey1"));
        el11.click();
        WebElement el12 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Part: PPP002\")"));
        el12.click();
        TestGesture.scrollById("searchTopic1_1");
        Thread.sleep(1000);
        WebElement el13 = driver.findElement(AppiumBy.accessibilityId("searchTopic1_1"));
        el13.click();
        WebElement el14 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-Apex:Apex\")"));
        el14.click();
        WebElement el15 = driver.findElement(AppiumBy.accessibilityId("searchTopic2"));
        el15.click();
        WebElement el16 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-LD:Lundie\")"));
        el16.click();
        TestGesture.scrollById("searchCust");
        Thread.sleep(1000);
        WebElement el17 = driver.findElement(AppiumBy.accessibilityId("searchCust"));
        el17.click();
        WebElement el18 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\")"));
        el18.click();
        WebElement el19 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Cust. ID: ADDISON\")"));
        el19.click();
        TestGesture.scrollById("resolutionText");
        Thread.sleep(1000);
        WebElement el20 = driver.findElement(AppiumBy.accessibilityId("resolutionText"));
        el20.click();
        el20.sendKeys("Replace the ink tank with a new one");
        WebElement el21 = driver.findElement(AppiumBy.accessibilityId("publishedSummary"));
        el21.click();
        el21.sendKeys("Published Summary");
        TestGesture.scrollById("publishedText");
        WebElement el22 = driver.findElement(AppiumBy.accessibilityId("publishedText"));
        el22.click();
        el22.sendKeys("Published");
        WebElement el23 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SAVE\")"));
        el23.click();
        WebElement el24 = driver.findElement(AppiumBy.id("android:id/button1"));
        el24.click();
        WebElement el25 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(16)"));
        el25.click();
        WebElement el26 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Create Service Call/Line\")"));
        el26.click();
        WebElement el27 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\")"));
        el27.click();
        WebElement el28 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"10\")"));
        el28.click();
        WebElement el29 = driver.findElement(AppiumBy.id("android:id/button1"));
        el29.click();
        WebElement el30 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\")"));
        el30.click();
        WebElement el31 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"STAND-Standard Service\")"));
        el31.click();
        WebElement el32 = driver.findElement(AppiumBy.className("android.widget.EditText"));
        el32.click();
        el32.sendKeys("0937");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        WebElement el33 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"OK\")"));
        el33.click();
        WebElement el34 = driver.findElement(AppiumBy.id("android:id/button1"));
        el34.click();
        WebElement el35 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(16)"));
        el35.click();
        WebElement el36 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Attachments\")"));
        el36.click();
        WebElement el37 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CHOOSE FILE\")"));
        el37.click();
        WebElement el38 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Gallery\")"));
        el38.click();
        WebElement el39 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/cbx"));
        el39.click();
        WebElement el40 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/tv_done"));
        el40.click();
        WebElement el41 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"OK\")"));
        el41.click();
        WebElement el42 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(16)"));
        el42.click();
        WebElement el43 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Case Detail\")"));
        el43.click();
        WebElement el44 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.widget.LinearLayout\").instance(7)"));
        el44.click();
        WebElement el45 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Complete\")"));
        el45.click();
        WebElement el46 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Milestone\")"));
        el46.click();
        //Thêm id cho các nút expand
        WebElement el47 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(0)"));
        el47.click();
        WebElement el48 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Complete:Task Completed\")"));
        el48.click();
        WebElement el49 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(3)"));
        el49.click();
        WebElement el50 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"INPR:In Process\")"));
        el50.click();
        WebElement el51 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(1)"));
        el51.click();
        WebElement el52 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1\")"));
        el52.click();
        WebElement el53 = driver.findElement(AppiumBy.id("android:id/button1"));
        el53.click();
        WebElement el54 = driver.findElement(AppiumBy.className("android.widget.EditText"));
        el54.click();
        el54.sendKeys("90");
        WebElement el55 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"UPDATE\")"));
        el55.click();
        WebElement el56 = driver.findElement(AppiumBy.id("android:id/button1"));
        el56.click();
        WebElement el57 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el57.click();
        WebElement el58 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Close Case\")"));
        el58.click();
        WebElement el59 = driver.findElement(AppiumBy.id("android:id/button1"));
        el59.click();

    }

    @Test
    public void DVTCall() throws InterruptedException {
        WebDriver driver = DriverManager.getDriver();
        WebElement el7 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call\")"));
        el7.click();
        WebElement el8 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el8.click();
        Thread.sleep(1000);
        WebElement el9 = driver.findElement(AppiumBy.id("android:id/text1"));
        el9.click();
        Thread.sleep(1000);
        WebElement el10 = driver.findElement(AppiumBy.accessibilityId("btnSearchCust"));
        el10.click();
        WebElement el11 = driver.findElement(AppiumBy.accessibilityId("iconSearch"));
        el11.click();
        WebElement el12 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(10)"));
        el12.click();
        TestGesture.scrollById("prioritySearch");
        WebElement el13 = driver.findElement(AppiumBy.accessibilityId("prioritySearch"));
        el13.click();
        WebElement el14 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"High\")"));
        el14.click();
        TestGesture.scrollById("calltypeSearch");
        WebElement el15 = driver.findElement(AppiumBy.accessibilityId("calltypeSearch"));
        el15.click();
        WebElement el16 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"STAND-Standard Service\")"));
        el16.click();
        TestGesture.scrollById("txtPoNumber");
        WebElement el17 = driver.findElement(AppiumBy.accessibilityId("txtPoNumber"));
        el17.click();
        el17.sendKeys("1315");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("txtCallHeadCmt");
        WebElement el18 = driver.findElement(AppiumBy.accessibilityId("txtCallHeadCmt"));
        el18.sendKeys("Call Header Comment");
        TestGesture.scrollById("txtInvcCmt");
        WebElement el19 = driver.findElement(AppiumBy.accessibilityId("txtInvcCmt"));
        el19.click();
        el19.sendKeys("Invoice Comment");
        WebElement el20 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el20.click();
        WebElement el21 = driver.findElement(AppiumBy.id("android:id/button1"));
        el21.click();
        TestGesture.scrollById("btnSearchPart");
        WebElement el22 = driver.findElement(AppiumBy.accessibilityId("btnSearchPart"));
        el22.click();
        WebElement el23 = driver.findElement(AppiumBy.accessibilityId("iconSearch"));
        el23.click();
        WebElement el24 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(12)"));
        el24.click();
        TestGesture.scrollById("txtProReasonDesc");
        WebElement el25 = driver.findElement(AppiumBy.accessibilityId("txtProReasonDesc"));
        el25.click();
        WebElement el26 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"UPGD:Field Upgrade\")"));
        el26.click();
        TestGesture.scrollById("txtPartDesc");
        WebElement el27 = driver.findElement(AppiumBy.accessibilityId("txtPartDesc"));
        el27.click();
        el27.sendKeys("Issue Description");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("IssueTopicID1Description");
        WebElement el28 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID1Description"));
        el28.click();
        WebElement el29 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-Apex:Apex\")"));
        el29.click();
        TestGesture.scrollById("IssueTopicID2Description");
        WebElement el30 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID2Description"));
        el30.click();
        WebElement el31 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-LD:Lundie\")"));
        el31.click();
        WebElement el32 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el32.click();
        WebElement el33 = driver.findElement(AppiumBy.id("android:id/button1"));
        el33.click();
        //WebElement el34 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        //el34.click();
        //WebElement el35 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Location\")"));
        //el35.click();
        //WebElement el36 = driver.findElement(AppiumBy.id("com.google.android.apps.maps:id/home_bottom_sheet_container"));
        //el36.click();
        //WebElement el37 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().resourceId(\"com.google.android.apps.maps:id/mod_app_bar_button_icon\").instance(2)"));
        //el37.click();
        //WebElement el38 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add to contacts\")"));
        //el38.click();
        //WebElement el39 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Cancel\")"));
        //el39.click();
        Thread.sleep(5000);
        WebElement el40 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el40.click();
        WebElement el41 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Job Safety Analysis\")"));
        el41.click();
        WebElement el42 = driver.findElement(AppiumBy.id("android:id/button1"));
        el42.click();
        WebElement el43 = driver.findElement(AppiumBy.accessibilityId("Observed_0"));
        el43.click();
        WebElement el44 = driver.findElement(AppiumBy.accessibilityId("Controlled_0"));
        el44.click();
        WebElement el45 = driver.findElement(AppiumBy.accessibilityId("comment_0"));
        el45.click();
        el45.sendKeys("1");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_1");
        WebElement el46 = driver.findElement(AppiumBy.accessibilityId("Observed_1"));
        el46.click();
        WebElement el47 = driver.findElement(AppiumBy.accessibilityId("Controlled_1"));
        el47.click();
        WebElement el48 = driver.findElement(AppiumBy.accessibilityId("comment_1"));
        el48.sendKeys("2");
        TestGesture.scrollById("Observed_2");
        WebElement el49 = driver.findElement(AppiumBy.accessibilityId("Observed_2"));
        el49.click();
        WebElement el50 = driver.findElement(AppiumBy.accessibilityId("Controlled_2"));
        el50.click();
        TestGesture.scrollById("comment_2");
        WebElement el51 = driver.findElement(AppiumBy.accessibilityId("comment_2"));
        el51.sendKeys("3");
        TestGesture.scrollById("Observed_3");
        WebElement el52 = driver.findElement(AppiumBy.accessibilityId("Observed_3"));
        el52.click();
        WebElement el53 = driver.findElement(AppiumBy.accessibilityId("Controlled_3"));
        el53.click();
        TestGesture.scrollById("comment_3");
        WebElement el54 = driver.findElement(AppiumBy.accessibilityId("comment_3"));
        el54.sendKeys("4");
        TestGesture.scrollById("Observed_4");
        WebElement el55 = driver.findElement(AppiumBy.accessibilityId("Observed_4"));
        el55.click();
        WebElement el56 = driver.findElement(AppiumBy.accessibilityId("Controlled_4"));
        el56.click();
        TestGesture.scrollById("comment_4");
        WebElement el57 = driver.findElement(AppiumBy.accessibilityId("comment_4"));
        el57.click();
        el57.sendKeys("5");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_5");
        WebElement el58 = driver.findElement(AppiumBy.accessibilityId("Observed_5"));
        el58.click();
        WebElement el59 = driver.findElement(AppiumBy.accessibilityId("Controlled_5"));
        el59.click();
        TestGesture.scrollById("comment_5");
        WebElement el60 = driver.findElement(AppiumBy.accessibilityId("comment_5"));
        el60.click();
        el60.sendKeys("6");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_6");
        WebElement el61 = driver.findElement(AppiumBy.accessibilityId("Observed_6"));
        el61.click();
        WebElement el62 = driver.findElement(AppiumBy.accessibilityId("Controlled_6"));
        el62.click();
        TestGesture.scrollById("comment_6");
        WebElement el63 = driver.findElement(AppiumBy.accessibilityId("comment_6"));
        el63.click();
        el63.sendKeys("7");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_7");
        WebElement el64 = driver.findElement(AppiumBy.accessibilityId("Observed_7"));
        el64.click();
        WebElement el65 = driver.findElement(AppiumBy.accessibilityId("Controlled_7"));
        el65.click();
        TestGesture.scrollById("comment_7");
        WebElement el66 = driver.findElement(AppiumBy.accessibilityId("comment_7"));
        el66.click();
        el66.sendKeys("8");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_8");
        WebElement el67 = driver.findElement(AppiumBy.accessibilityId("Observed_8"));
        el67.click();
        WebElement el68 = driver.findElement(AppiumBy.accessibilityId("Controlled_8"));
        el68.click();
        TestGesture.scrollById("comment_8");
        WebElement el69 = driver.findElement(AppiumBy.accessibilityId("comment_8"));
        el69.click();
        el69.sendKeys("9");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_9");
        WebElement el70 = driver.findElement(AppiumBy.accessibilityId("Observed_9"));
        el70.click();
        WebElement el71 = driver.findElement(AppiumBy.accessibilityId("Controlled_9"));
        el71.click();
        TestGesture.scrollById("comment_9");
        WebElement el72 = driver.findElement(AppiumBy.accessibilityId("comment_9"));
        el72.click();
        el72.sendKeys("10");
        WebElement el73 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el73.click();
        WebElement el74 = driver.findElement(AppiumBy.id("android:id/button1"));
        el74.click();
        WebElement el75 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el75.click();
        Thread.sleep(5000);
        WebElement el76 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Attachment\")"));
        el76.click();
        WebElement el77 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CHOOSE FILE\")"));
        el77.click();
        WebElement el78 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Gallery\")"));
        el78.click();
        WebElement el79 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/tv_done"));
        el79.click();
        WebElement el80 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CHOOSE FILE\")"));
        el80.click();
        WebElement el81 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Gallery\")"));
        el81.click();
        WebElement el82 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/cbx"));
        el82.click();
        WebElement el83 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/tv_done"));
        el83.click();
        WebElement el84 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"OK\")"));
        el84.click();
        Thread.sleep(2000);
        WebElement el85 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el85.click();
        WebElement el86 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Customer Signature Confirmation\")"));
        el86.click();
        WebElement el87 = driver.findElement(AppiumBy.className("android.view.View"));
        el87.click();
        WebElement el88 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"DONE\")"));
        el88.click();
        Thread.sleep(2000);
        WebElement el89 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el89.click();
        WebElement el90 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Detail\")"));
        el90.click();
        WebElement el91 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el91.click();
        WebElement el92 = driver.findElement(AppiumBy.id("android:id/button2"));
        el92.click();
        WebElement el93 = driver.findElement(AppiumBy.accessibilityId("Tabs-Lines"));
        el93.click();
        WebElement el94 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el94.click();
        WebElement el95 = driver.findElement(AppiumBy.id("android:id/text1"));
        el95.click();
        WebElement el96 = driver.findElement(AppiumBy.accessibilityId("btnSearchPart"));
        el96.click();
        WebElement el97 = driver.findElement(AppiumBy.accessibilityId("btnSearch"));
        el97.click();
        Thread.sleep(2000);
        WebElement el98 = driver.findElement(AppiumBy.xpath("//android.widget.FrameLayout[@resource-id=\"android:id/content\"]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]"));
        el98.click();
        WebElement el99 = driver.findElement(AppiumBy.accessibilityId("txtPartDesc"));
        el99.sendKeys("Issue Des Line 2");
        WebElement el100 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID1Description"));
        el100.click();
        WebElement el101 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-YB:Yallambee\")"));
        el101.click();
        WebElement el102 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID2Description"));
        el102.click();
        WebElement el103 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-KL:K-Lodge\")"));
        el103.click();
        WebElement el104 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el104.click();
        WebElement el105 = driver.findElement(AppiumBy.id("android:id/button1"));
        el105.click();
        Thread.sleep(2000);
        WebElement el106 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(12)"));
        el106.click();
        WebElement el107 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Edit Line\")"));
        el107.click();
        Thread.sleep(2000);
        WebElement el108 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1\").instance(1)"));
        el108.click();
        WebElement el109 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SAVE\")"));
        el109.click();
        WebElement el110 = driver.findElement(AppiumBy.id("android:id/button1"));
        el110.click();
        WebElement el111 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el111.click();
        WebElement el112 = driver.findElement(AppiumBy.id("android:id/button2"));
        el112.click();
        Thread.sleep(2000);
        WebElement el113 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(12)"));
        el113.click();
        WebElement el114 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Job Details\")"));
        el114.click();
        WebElement el115 = driver.findElement(AppiumBy.accessibilityId("Tabs-Operations"));
        el115.click();
        WebElement el116 = driver.findElement(AppiumBy.accessibilityId("Tabs-Materials"));
        el116.click();
        WebElement el117 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el117.click();
        WebElement el118 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add Material\")"));
        el118.click();
        Thread.sleep(2000);
        WebElement el119 = driver.findElement(AppiumBy.xpath("//android.view.ViewGroup[@content-desc=\"gridPart\"]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el119.click();
        WebElement el120 = driver.findElement(AppiumBy.accessibilityId("getUnitPrice"));
        el120.click();
        WebElement el121 = driver.findElement(AppiumBy.id("android:id/button1"));
        el121.click();
        WebElement el122 = driver.findElement(AppiumBy.accessibilityId("update"));
        el122.click();
        WebElement el123 = driver.findElement(AppiumBy.id("android:id/button1"));
        el123.click();
        WebElement el124 = driver.findElement(AppiumBy.accessibilityId("Tabs-Operations"));
        el124.click();
        WebElement el125 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el125.click();
        WebElement el126 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add Operation\")"));
        el126.click();
        Thread.sleep(2000);
        WebElement el127 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.widget.TextView\").instance(4)"));
        el127.click();
        WebElement el128 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Technician\")"));
        el128.click();
        el128.click();
        WebElement el129 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"0\").instance(0)"));
        el129.click();
        el129.sendKeys("5");
        WebElement el130 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SAVE\")"));
        el130.click();
        WebElement el131 = driver.findElement(AppiumBy.id("android:id/button1"));
        el131.click();
        WebElement el132 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el132.click();
        WebElement el133 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el133.click();
        WebElement el134 = driver.findElement(AppiumBy.id("android:id/button2"));
        el134.click();
        WebElement el135 = driver.findElement(AppiumBy.accessibilityId("Tabs-Technicians"));
        el135.click();
        WebElement el136 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el136.click();
        WebElement el137 = driver.findElement(AppiumBy.id("android:id/text1"));
        el137.click();
        WebElement el138 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.Switch"));
        el138.click();
        WebElement el139 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"ASSIGN\")"));
        el139.click();
        WebElement el140 = driver.findElement(AppiumBy.id("android:id/button1"));
        el140.click();
        WebElement el141 = driver.findElement(AppiumBy.accessibilityId("Tabs-Header"));
        el141.click();
        WebElement el142 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el142.click();
        WebElement el143 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Preview Service Report\")"));
        el143.click();
        WebElement el144 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el144.click();
        WebElement el145 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Print to File\")"));
        el145.click();
        Thread.sleep(5000);
        WebElement el146 = driver.findElement(AppiumBy.className("android.widget.ImageButton"));
        el146.click();
        WebElement el147 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el147.click();
        WebElement el148 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Close Service Call\")"));
        el148.click();
        WebElement el149 = driver.findElement(AppiumBy.id("android:id/button1"));
        el149.click();
        WebElement el150 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el150.click();
        WebElement el151 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el151.click();
        WebElement el152 = driver.findElement(AppiumBy.id("android:id/button2"));
        el152.click();
        WebElement el153 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el153.click();
        Thread.sleep(2000);
        WebElement el154 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(2)"));
        el154.click();
        Thread.sleep(2000);
        WebElement el155 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(0)"));
        el155.click();
        WebElement el156 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el156.click();
        WebElement el157 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Work Details\")"));
        el157.click();
        WebElement el158 = driver.findElement(AppiumBy.accessibilityId("btnStartJob"));
        el158.click();
        WebElement el159 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el159.click();
        WebElement el160 = driver.findElement(AppiumBy.id("android:id/button2"));
        el160.click();
        WebElement el161 = driver.findElement(AppiumBy.accessibilityId("Tabs-Materials"));
        el161.click();
        WebElement el162 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el162.click();
        WebElement el163 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add and Issue Material\")"));
        el163.click();
        Thread.sleep(2000);
        WebElement el164 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(10)"));
        el164.click();
        WebElement el165 = driver.findElement(AppiumBy.accessibilityId("getUnitPrice"));
        el165.click();
        WebElement el166 = driver.findElement(AppiumBy.id("android:id/button1"));
        el166.click();
        WebElement el167 = driver.findElement(AppiumBy.accessibilityId("issueMtl"));
        el167.click();
        WebElement el168 = driver.findElement(AppiumBy.accessibilityId("tranQty"));
        el168.click();
        el168.sendKeys("1");
        WebElement el169 = driver.findElement(AppiumBy.accessibilityId("submit"));
        el169.click();
        WebElement el170 = driver.findElement(AppiumBy.id("android:id/button1"));
        el170.click();
        WebElement el171 = driver.findElement(AppiumBy.accessibilityId("Tabs-Tasks"));
        el171.click();
        WebElement el172 = driver.findElement(AppiumBy.accessibilityId("btnCancel"));
        el172.click();
        Thread.sleep(2000);
        WebElement el173 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el173.click();
        WebElement el174 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Technician Signature Confirmation\")"));
        el174.click();
        WebElement el175 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"DONE\")"));
        el175.click();
        Thread.sleep(2000);
        WebElement el176 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el176.click();
        WebElement el177 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Work Details\")"));
        el177.click();
        WebElement el178 = driver.findElement(AppiumBy.accessibilityId("btnStartJob"));
        el178.click();
        WebElement el179 = driver.findElement(AppiumBy.id("android:id/button1"));
        el179.click();
        WebElement el180 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SUBMIT\")"));
        el180.click();
        WebElement el181 = driver.findElement(AppiumBy.id("android:id/button1"));
        el181.click();
        WebElement el182 = driver.findElement(AppiumBy.id("android:id/button2"));
        el182.click();
        WebElement el183 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el183.click();
        WebElement el184 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el184.click();
        Thread.sleep(2000);
        WebElement el185 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(26)"));
        el185.click();
        Thread.sleep(2000);
        WebElement el186 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el186.click();
        WebElement el187 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Detail\")"));
        el187.click();
        WebElement el188 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el188.click();
        WebElement el189 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Close Service Call\")"));
        el189.click();
        WebElement el190 = driver.findElement(AppiumBy.accessibilityId("save"));
        el190.click();
        WebElement el191 = driver.findElement(AppiumBy.id("android:id/button1"));
        el191.click();
        WebElement el192 = driver.findElement(AppiumBy.accessibilityId("changeStatus"));
        el192.click();
        WebElement el193 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CLOSED\")"));
        el193.click();
        }


    @Test
        public void DVTJobSafety() throws InterruptedException {
        WebDriver driver = DriverManager.getDriver();
        WebElement el40 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el40.click();
        WebElement el41 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Job Safety Analysis\")"));
        el41.click();
        WebElement el42 = driver.findElement(AppiumBy.id("android:id/button1"));
        el42.click();
        WebElement el43 = driver.findElement(AppiumBy.accessibilityId("Observed_0"));
        el43.click();
        WebElement el44 = driver.findElement(AppiumBy.accessibilityId("Controlled_0"));
        el44.click();
        WebElement el45 = driver.findElement(AppiumBy.accessibilityId("comment_0"));
        el45.click();
        el45.sendKeys("1");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_1");
        WebElement el46 = driver.findElement(AppiumBy.accessibilityId("Observed_1"));
        el46.click();
        WebElement el47 = driver.findElement(AppiumBy.accessibilityId("Controlled_1"));
        el47.click();
        WebElement el48 = driver.findElement(AppiumBy.accessibilityId("comment_1"));
        el48.sendKeys("2");
        TestGesture.scrollById("Observed_2");
        WebElement el49 = driver.findElement(AppiumBy.accessibilityId("Observed_2"));
        el49.click();
        WebElement el50 = driver.findElement(AppiumBy.accessibilityId("Controlled_2"));
        el50.click();
        TestGesture.scrollById("comment_2");
        WebElement el51 = driver.findElement(AppiumBy.accessibilityId("comment_2"));
        el51.sendKeys("3");
        TestGesture.scrollById("Observed_3");
        WebElement el52 = driver.findElement(AppiumBy.accessibilityId("Observed_3"));
        el52.click();
        WebElement el53 = driver.findElement(AppiumBy.accessibilityId("Controlled_3"));
        el53.click();
        TestGesture.scrollById("comment_3");
        WebElement el54 = driver.findElement(AppiumBy.accessibilityId("comment_3"));
        el54.sendKeys("4");
        TestGesture.scrollById("Observed_4");
        WebElement el55 = driver.findElement(AppiumBy.accessibilityId("Observed_4"));
        el55.click();
        WebElement el56 = driver.findElement(AppiumBy.accessibilityId("Controlled_4"));
        el56.click();
        TestGesture.scrollById("comment_4");
        WebElement el57 = driver.findElement(AppiumBy.accessibilityId("comment_4"));
        el57.click();
        el57.sendKeys("5");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_5");
        WebElement el58 = driver.findElement(AppiumBy.accessibilityId("Observed_5"));
        el58.click();
        WebElement el59 = driver.findElement(AppiumBy.accessibilityId("Controlled_5"));
        el59.click();
        TestGesture.scrollById("comment_5");
        WebElement el60 = driver.findElement(AppiumBy.accessibilityId("comment_5"));
        el60.click();
        el60.sendKeys("6");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_6");
        WebElement el61 = driver.findElement(AppiumBy.accessibilityId("Observed_6"));
        el61.click();
        WebElement el62 = driver.findElement(AppiumBy.accessibilityId("Controlled_6"));
        el62.click();
        TestGesture.scrollById("comment_6");
        WebElement el63 = driver.findElement(AppiumBy.accessibilityId("comment_6"));
        el63.click();
        el63.sendKeys("7");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_7");
        WebElement el64 = driver.findElement(AppiumBy.accessibilityId("Observed_7"));
        el64.click();
        WebElement el65 = driver.findElement(AppiumBy.accessibilityId("Controlled_7"));
        el65.click();
        TestGesture.scrollById("comment_7");
        WebElement el66 = driver.findElement(AppiumBy.accessibilityId("comment_7"));
        el66.click();
        el66.sendKeys("8");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_8");
        WebElement el67 = driver.findElement(AppiumBy.accessibilityId("Observed_8"));
        el67.click();
        WebElement el68 = driver.findElement(AppiumBy.accessibilityId("Controlled_8"));
        el68.click();
        TestGesture.scrollById("comment_8");
        WebElement el69 = driver.findElement(AppiumBy.accessibilityId("comment_8"));
        el69.click();
        el69.sendKeys("9");
        ((AppiumDriver)driver).executeScript("mobile: pressKey", Map.ofEntries(Map.entry("keycode", 4)));
        TestGesture.scrollById("Observed_9");
        WebElement el70 = driver.findElement(AppiumBy.accessibilityId("Observed_9"));
        el70.click();
        WebElement el71 = driver.findElement(AppiumBy.accessibilityId("Controlled_9"));
        el71.click();
        TestGesture.scrollById("comment_9");
        WebElement el72 = driver.findElement(AppiumBy.accessibilityId("comment_9"));
        el72.click();
        el72.sendKeys("10");
        WebElement el73 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el73.click();
        WebElement el74 = driver.findElement(AppiumBy.id("android:id/button1"));
        el74.click();
        WebElement el75 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el75.click();
        WebElement el76 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Attachment\")"));
        el76.click();
        WebElement el77 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CHOOSE FILE\")"));
        el77.click();
        WebElement el78 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Gallery\")"));
        el78.click();
        WebElement el79 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/tv_done"));
        el79.click();
        WebElement el80 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CHOOSE FILE\")"));
        el80.click();
        WebElement el81 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Gallery\")"));
        el81.click();
        WebElement el82 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/cbx"));
        el82.click();
        WebElement el83 = driver.findElement(AppiumBy.id("pocketv.datavtech.application:id/tv_done"));
        el83.click();
        WebElement el84 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"OK\")"));
        el84.click();
        WebElement el85 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el85.click();
        WebElement el86 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Customer Signature Confirmation\")"));
        el86.click();
        WebElement el87 = driver.findElement(AppiumBy.className("android.view.View"));
        el87.click();
        WebElement el88 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"DONE\")"));
        el88.click();
        WebElement el89 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el89.click();
        WebElement el90 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Detail\")"));
        el90.click();
        WebElement el91 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el91.click();
        WebElement el92 = driver.findElement(AppiumBy.id("android:id/button2"));
        el92.click();
        WebElement el93 = driver.findElement(AppiumBy.accessibilityId("Tabs-Lines"));
        el93.click();
        WebElement el94 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el94.click();
        WebElement el95 = driver.findElement(AppiumBy.id("android:id/text1"));
        el95.click();
        WebElement el96 = driver.findElement(AppiumBy.accessibilityId("btnSearchPart"));
        el96.click();
        WebElement el97 = driver.findElement(AppiumBy.accessibilityId("btnSearch"));
        el97.click();
        WebElement el98 = driver.findElement(AppiumBy.xpath("//android.widget.FrameLayout[@resource-id=\"android:id/content\"]/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[5]"));
        el98.click();
        WebElement el99 = driver.findElement(AppiumBy.accessibilityId("txtPartDesc"));
        el99.sendKeys("Issue Des Line 2");
        WebElement el100 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID1Description"));
        el100.click();
        WebElement el101 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-YB:Yallambee\")"));
        el101.click();
        WebElement el102 = driver.findElement(AppiumBy.accessibilityId("IssueTopicID2Description"));
        el102.click();
        WebElement el103 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1-KL:K-Lodge\")"));
        el103.click();
        WebElement el104 = driver.findElement(AppiumBy.accessibilityId("btnSave"));
        el104.click();
        WebElement el105 = driver.findElement(AppiumBy.id("android:id/button1"));
        el105.click();
        WebElement el106 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(12)"));
        el106.click();
        WebElement el107 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Edit Line\")"));
        el107.click();
        WebElement el108 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"1\").instance(1)"));
        el108.click();
        WebElement el109 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SAVE\")"));
        el109.click();
        WebElement el110 = driver.findElement(AppiumBy.id("android:id/button1"));
        el110.click();
        WebElement el111 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el111.click();
        WebElement el112 = driver.findElement(AppiumBy.id("android:id/button2"));
        el112.click();
        WebElement el113 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(12)"));
        el113.click();
        WebElement el114 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Job Details\")"));
        el114.click();
        WebElement el115 = driver.findElement(AppiumBy.accessibilityId("Tabs-Operations"));
        el115.click();
        WebElement el116 = driver.findElement(AppiumBy.accessibilityId("Tabs-Materials"));
        el116.click();
        WebElement el117 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el117.click();
        WebElement el118 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add Material\")"));
        el118.click();
        WebElement el119 = driver.findElement(AppiumBy.xpath("//android.view.ViewGroup[@content-desc=\"gridPart\"]/android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el119.click();
        WebElement el120 = driver.findElement(AppiumBy.accessibilityId("getUnitPrice"));
        el120.click();
        WebElement el121 = driver.findElement(AppiumBy.id("android:id/button1"));
        el121.click();
        WebElement el122 = driver.findElement(AppiumBy.accessibilityId("update"));
        el122.click();
        WebElement el123 = driver.findElement(AppiumBy.id("android:id/button1"));
        el123.click();
        WebElement el124 = driver.findElement(AppiumBy.accessibilityId("Tabs-Operations"));
        el124.click();
        WebElement el125 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el125.click();
        WebElement el126 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add Operation\")"));
        el126.click();
        WebElement el127 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.widget.TextView\").instance(4)"));
        el127.click();
        WebElement el128 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Technician\")"));
        el128.click();
        el128.click();
        WebElement el129 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"0\").instance(0)"));
        el129.click();
        el129.sendKeys("5");
        WebElement el130 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SAVE\")"));
        el130.click();
        WebElement el131 = driver.findElement(AppiumBy.id("android:id/button1"));
        el131.click();
        WebElement el132 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el132.click();
        WebElement el133 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el133.click();
        WebElement el134 = driver.findElement(AppiumBy.id("android:id/button2"));
        el134.click();
        WebElement el135 = driver.findElement(AppiumBy.accessibilityId("Tabs-Technicians"));
        el135.click();
        WebElement el136 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el136.click();
        WebElement el137 = driver.findElement(AppiumBy.id("android:id/text1"));
        el137.click();
        WebElement el138 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.Switch"));
        el138.click();
        WebElement el139 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"ASSIGN\")"));
        el139.click();
        WebElement el140 = driver.findElement(AppiumBy.id("android:id/button1"));
        el140.click();
        WebElement el141 = driver.findElement(AppiumBy.accessibilityId("Tabs-Header"));
        el141.click();
        WebElement el142 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el142.click();
        WebElement el143 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Preview Service Report\")"));
        el143.click();
        WebElement el144 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el144.click();
        WebElement el145 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Print to File\")"));
        el145.click();
        WebElement el146 = driver.findElement(AppiumBy.className("android.widget.ImageButton"));
        el146.click();
        WebElement el147 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el147.click();
        WebElement el148 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Close Service Call\")"));
        el148.click();
        WebElement el149 = driver.findElement(AppiumBy.id("android:id/button1"));
        el149.click();
        WebElement el150 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el150.click();
        WebElement el151 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el151.click();
        WebElement el152 = driver.findElement(AppiumBy.id("android:id/button2"));
        el152.click();
        WebElement el153 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el153.click();
        WebElement el154 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(2)"));
        el154.click();
        WebElement el155 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"\").instance(0)"));
        el155.click();
        WebElement el156 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el156.click();
        WebElement el157 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Work Details\")"));
        el157.click();
        WebElement el158 = driver.findElement(AppiumBy.accessibilityId("btnStartJob"));
        el158.click();
        WebElement el159 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el159.click();
        WebElement el160 = driver.findElement(AppiumBy.id("android:id/button2"));
        el160.click();
        WebElement el161 = driver.findElement(AppiumBy.accessibilityId("Tabs-Materials"));
        el161.click();
        WebElement el162 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el162.click();
        WebElement el163 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Add and Issue Material\")"));
        el163.click();
        WebElement el164 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(10)"));
        el164.click();
        WebElement el165 = driver.findElement(AppiumBy.accessibilityId("getUnitPrice"));
        el165.click();
        WebElement el166 = driver.findElement(AppiumBy.id("android:id/button1"));
        el166.click();
        WebElement el167 = driver.findElement(AppiumBy.accessibilityId("issueMtl"));
        el167.click();
        WebElement el168 = driver.findElement(AppiumBy.accessibilityId("tranQty"));
        el168.click();
        el168.sendKeys("1");
        WebElement el169 = driver.findElement(AppiumBy.accessibilityId("submit"));
        el169.click();
        WebElement el170 = driver.findElement(AppiumBy.id("android:id/button1"));
        el170.click();
        WebElement el171 = driver.findElement(AppiumBy.accessibilityId("Tabs-Tasks"));
        el171.click();
        WebElement el172 = driver.findElement(AppiumBy.accessibilityId("btnCancel"));
        el172.click();
        WebElement el173 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el173.click();
        WebElement el174 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Technician Signature Confirmation\")"));
        el174.click();
        WebElement el175 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"DONE\")"));
        el175.click();
        WebElement el176 = driver.findElement(AppiumBy.xpath("//android.widget.ScrollView/android.view.ViewGroup/android.view.ViewGroup[1]"));
        el176.click();
        WebElement el177 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Work Details\")"));
        el177.click();
        WebElement el178 = driver.findElement(AppiumBy.accessibilityId("btnStartJob"));
        el178.click();
        WebElement el179 = driver.findElement(AppiumBy.id("android:id/button1"));
        el179.click();
        WebElement el180 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"SUBMIT\")"));
        el180.click();
        WebElement el181 = driver.findElement(AppiumBy.id("android:id/button1"));
        el181.click();
        WebElement el182 = driver.findElement(AppiumBy.id("android:id/button2"));
        el182.click();
        WebElement el183 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el183.click();
        WebElement el184 = driver.findElement(AppiumBy.accessibilityId("Back"));
        el184.click();
        WebElement el185 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(26)"));
        el185.click();
        WebElement el186 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().className(\"android.view.ViewGroup\").instance(14)"));
        el186.click();
        WebElement el187 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Service Call Detail\")"));
        el187.click();
        WebElement el188 = driver.findElement(AppiumBy.accessibilityId("submenu"));
        el188.click();
        WebElement el189 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"Close Service Call\")"));
        el189.click();
        WebElement el190 = driver.findElement(AppiumBy.accessibilityId("save"));
        el190.click();
        WebElement el191 = driver.findElement(AppiumBy.id("android:id/button1"));
        el191.click();
        WebElement el192 = driver.findElement(AppiumBy.accessibilityId("changeStatus"));
        el192.click();
        WebElement el193 = driver.findElement(AppiumBy.androidUIAutomator("new UiSelector().text(\"CLOSED\")"));
        el193.click();
        }
}





